language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - "1.11"
  - tip
  - master
os:
  - linux
  - osx
dist: trusty
sudo: false
install: true
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
